_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.6
            "6": 4.50.3
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
